# SITE CONFIGURATION
title: Muhammad Tahir Ashraf, Ph.D. # your site title
author: Muhammad Tahir Ashraf, Ph.D. # You :P
description: > # Meta description of Homepage
  Notes on broad topics including Process Engineering, Chemical Engineering, Biorefinery, Renewable Energy, Data Analysis, and Data Science. 
  # Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tahircpe.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Muhammad Tahir Ashraf
  links:
    - https://twitter.com/tahircpe
    #- https://www.facebook.com/tahirce14
    - https://www.linkedin.com/in/tahircpe
    - https://plus.google.com/+tahircpe
    - https://github.com/tahircpe
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Notes on Process Engineering and Data Science Topics


hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: tahircpe@gmail.com # email for form submission

twitter_username: tahircpe # replace with your_twitter_username or comment to remove link from footer

github_username:  tahircpe # replace with your_github_username or comment to remove link from footer

#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: tahircpe # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
